const ORDER_STATUS_ID = {
  SUBMITTED: 1,
  IN_PROGRESS: 2,
  COMPLETED: 3,
  CANCELLED: 4,
};

const ORDER_STATUS_ID_TO_TEXT = {
  [ORDER_STATUS_ID.SUBMITTED]: "Submitted",
  [ORDER_STATUS_ID.IN_PROGRESS]: "In Progress",
  [ORDER_STATUS_ID.COMPLETED]: "Completed",
  [ORDER_STATUS_ID.CANCELLED]: "Cancelled",
};

export { ORDER_STATUS_ID, ORDER_STATUS_ID_TO_TEXT };
